# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqr56-QWf6SGncelm5Mv2RUWCvKwvsoS
"""

print("Hello! My sentiment analyzer is starting 🚀")

!pip install pandas scikit-learn matplotlib

import pandas as pd

reviews = {
    "review": [
        "I absolutely love this product!",
        "Amazing quality, I would buy it again.",
        "This is fantastic and works perfectly.",
        "Very happy with my purchase.",
        "The product is excellent.",
        "I hate this product.",
        "Terrible quality, completely disappointed.",
        "This was a waste of money.",
        "It broke after one day.",
        "Absolutely horrible experience.",
        "It is okay, nothing special.",
        "The product is average.",
        "It works, but it could be better.",
        "Not bad, but not amazing either.",
        "It is fine for the price."
    ],

    "sentiment": [
        "positive",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "negative",
        "negative",
        "neutral",
        "neutral",
        "neutral",
        "neutral",
        "neutral"
    ]
}

df = pd.DataFrame(reviews)

df

from sklearn.model_selection import train_test_split

X = df["review"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training reviews:", len(X_train))
print("Testing reviews:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

print("Our text has been converted into numbers!")
print("Training data shape:", X_train_vectors.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_vectors, y_train)

print("Model trained successfully! 🤖")

from sklearn.metrics import accuracy_score

predictions = model.predict(X_test_vectors)

accuracy = accuracy_score(y_test, predictions)

print("Model accuracy:", accuracy)

new_reviews = [
    "I really love this product!",
    "This product is awful and disappointing.",
    "It is okay, nothing special."
]

new_vectors = vectorizer.transform(new_reviews)

predictions = model.predict(new_vectors)

for review, prediction in zip(new_reviews, predictions):
    print(f"Review: {review}")
    print(f"Prediction: {prediction}")
    print()

from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups(
    subset="train",
    categories=["rec.sport.baseball", "sci.med"],
    remove=("headers", "footers", "quotes")
)

print("Number of examples:", len(data.data))

import nltk

nltk.download("movie_reviews")

from nltk.corpus import movie_reviews

documents = [
    (list(movie_reviews.words(fileid)), category)
    for category in movie_reviews.categories()
    for fileid in movie_reviews.fileids(category)
]

print("Number of reviews:", len(documents))

import pandas as pd

reviews = []

for words, sentiment in documents:
    text = " ".join(words)
    reviews.append({
        "review": text,
        "sentiment": sentiment
    })

df = pd.DataFrame(reviews)

print(df.head())
print("\nNumber of reviews:", len(df))

from sklearn.model_selection import train_test_split

X = df["review"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training reviews:", len(X_train))
print("Testing reviews:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

print("Training data shape:", X_train_vectors.shape)
print("Testing data shape:", X_test_vectors.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_vectors, y_train)

print("Model trained successfully! 🤖")

from sklearn.metrics import accuracy_score

predictions = model.predict(X_test_vectors)

accuracy = accuracy_score(y_test, predictions)

print(f"Model accuracy: {accuracy:.2%}")

while True:
    review = input("Enter a review (or type 'quit' to stop): ")

    if review.lower() == "quit":
        break

    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)[0]

    print("Sentiment:", prediction)
    print()

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, predictions))

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_test,
    predictions,
    display_labels=["Negative", "Positive"]
)

plt.title("Sentiment Analysis — Confusion Matrix")
plt.show()

!pip install gradio

import gradio as gr

def analyze_sentiment(review):
    review_vector = vectorizer.transform([review])

    prediction = model.predict(review_vector)[0]
    probabilities = model.predict_proba(review_vector)[0]

    confidence = max(probabilities) * 100

    if prediction == "pos":
        sentiment = "😊 Positive"
    else:
        sentiment = "😞 Negative"

    return f"{sentiment} — {confidence:.1f}% confidence"

app = gr.Interface(
    fn=analyze_sentiment,
    inputs=gr.Textbox(
        label="Enter a movie review",
        placeholder="Type your review here..."
    ),
    outputs=gr.Textbox(label="Sentiment"),
    title="🎬 Movie Review Sentiment Analyzer",
    description="Enter a movie review and our machine-learning model will predict whether it is positive or negative."
)

app.launch()

def analyze_sentiment(review):
    review_vector = vectorizer.transform([review])

    prediction = model.predict(review_vector)[0]
    probabilities = model.predict_proba(review_vector)[0]

    confidence = max(probabilities) * 100

    if prediction == "pos":
        sentiment = "😊 Positive"
    else:
        sentiment = "😞 Negative"

    return f"{sentiment} — {confidence:.1f}% confidence"